In [ ]:
import numpy as np

In [92]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7, 4)
data

array([[ 0.84201319,  0.97876183, -1.06351575, -0.36365756],
       [-0.71364538, -0.6863147 ,  1.8073909 , -0.71715576],
       [ 1.49174432, -1.91034579, -1.29879019,  0.32310459],
       [ 0.67557827, -0.80133792, -0.38447693, -1.33700233],
       [ 0.22240448, -2.68881631, -1.08885439, -0.21044539],
       [-0.46678301, -0.08785038,  0.85315479,  0.28628722],
       [ 0.02128153, -1.38451189, -0.73427852,  1.15736571]])

In [ ]:
data[0][1] = 2

In [85]:
x = data[data<0]

In [90]:
x[2] = 4

In [79]:
x = data[names=='Bob']

In [82]:
x

array([[ 0.38103655,  2.01030736,  0.07341259,  0.63390749],
       [ 1.32908421,  4.        , -0.72247372, -0.36017441]])

In [88]:
x[1][1] = 4.0

TypeError: 'numpy.float64' object does not support item assignment

In [75]:
x = data[:2]
x

array([[-0.19414991,  0.08878912,  2.33589698,  1.14578226],
       [-0.01180346, -1.16705712,  0.02830586,  0.0178139 ]])

In [ ]:
x[1][1] = 4

In [91]:
data

array([[-0.52365137,  1.04457458,  0.81071029, -2.05116296],
       [ 0.24650792, -0.80240642, -1.62281986,  0.70121538],
       [ 0.27771398,  0.25099629, -1.11292561,  0.99711327],
       [ 0.06874627, -0.94185741,  0.5703814 , -0.05492035],
       [ 0.59462406, -0.91702874,  0.8183826 ,  1.48561109],
       [-2.14012851,  0.28576952,  0.73256379,  1.0290031 ],
       [ 0.03220184, -0.14137284,  1.02368175,  0.81562402]])

In [ ]:
data[names=='Bob'] = 5

In [ ]:
b

In [ ]:
b = 4

In [ ]:
data